USE [2022DBFall_Group_1_DB]
GO

/*
Drop all Stored Procedures
*/
DROP PROCEDURE IF EXISTS [dbo].[usp_revenue_analysis]
GO

DROP PROCEDURE IF EXISTS [dbo].[usp_customer_trends]
GO

/*
Drop all Views
*/
DROP VIEW IF EXISTS [dbo].[REVENUE_ANALYSIS_AVG_VW]
GO

DROP VIEW IF EXISTS [dbo].[REVENUE_ANALYSIS_VW]
GO

DROP VIEW IF EXISTS [dbo].[PROPULAR_PRODUCTS_VW]
GO

DROP VIEW IF EXISTS [dbo].[PRODUCTS_SHIPDAYS_VW] 
GO

DROP VIEW IF EXISTS [dbo].[SALES_PROMOTIONS_VW] 
GO

DROP VIEW IF EXISTS [dbo].[CUSTOMER_TREND_IN_VW]
GO

DROP VIEW IF EXISTS [dbo].[CUSTOMER_TREND_VW]
GO

/*
Drop all constraints
*/
IF OBJECT_ID('UQ_PROD_NAME') IS NOT NULL
	ALTER TABLE dbo.PRODUCTS DROP CONSTRAINT UQ_PROD_NAME
GO

IF OBJECT_ID('CK_COUNTRY_REGION') IS NOT NULL 
	ALTER TABLE dbo.CUSTOMERS_COUNTRY DROP CONSTRAINT CK_COUNTRY_REGION 
GO

IF OBJECT_ID('CK_COUNTRY_SUBREGION') IS NOT NULL 
	ALTER TABLE dbo.CUSTOMERS_COUNTRY DROP CONSTRAINT CK_COUNTRY_SUBREGION 
GO

IF OBJECT_ID('CK_CUST_GENDER') IS NOT NULL
	ALTER TABLE dbo.CUSTOMERS DROP CONSTRAINT CK_CUST_GENDER
GO

IF OBJECT_ID('CK_CUST_MARITAL_STATUS') IS NOT NULL
	ALTER TABLE dbo.CUSTOMERS DROP CONSTRAINT CK_CUST_MARITAL_STATUS
GO

IF OBJECT_ID('CK_MIN_PRICE') IS NOT NULL
	ALTER TABLE dbo.PRODUCTS DROP CONSTRAINT CK_MIN_PRICE 
GO

IF OBJECT_ID('CK_PROMO_END_DATE') IS NOT NULL
	ALTER TABLE dbo.PROMOTIONS DROP CONSTRAINT CK_PROMO_END_DATE
GO

IF OBJECT_ID('CK_SHIPPING_DATE') IS NOT NULL
	ALTER TABLE dbo.SALES DROP CONSTRAINT CK_SHIPPING_DATE
GO

IF OBJECT_ID('CK_PAYMENT_DATE') IS NOT NULL
	ALTER TABLE dbo.SALES DROP CONSTRAINT CK_PAYMENT_DATE 
GO

IF OBJECT_ID('CK_QUANTITY_SOLD') IS NOT NULL
	ALTER TABLE dbo.SALES DROP CONSTRAINT CK_QUANTITY_SOLD
GO

IF OBJECT_ID('CK_UNIT_PRICE') IS NOT NULL
	ALTER TABLE dbo.SALES DROP CONSTRAINT CK_UNIT_PRICE
GO

IF OBJECT_ID('FK_COUNTRY_ID') IS NOT NULL
	ALTER TABLE dbo.CUSTOMERS DROP CONSTRAINT FK_COUNTRY_ID
GO

IF OBJECT_ID('FK_CUST_INCOME_CATEGORY') IS NOT NULL
	ALTER TABLE dbo.CUSTOMERS DROP CONSTRAINT FK_CUST_INCOME_CATEGORY
GO

IF OBJECT_ID('FK_PROD_SUBCATEGORY') IS NOT NULL
	ALTER TABLE dbo.PRODUCTS DROP CONSTRAINT FK_PROD_SUBCATEGORY
GO

IF OBJECT_ID('FK_PROMO_SUBCATEGORY_ID') IS NOT NULL
	ALTER TABLE dbo.PROMOTIONS DROP CONSTRAINT FK_PROMO_SUBCATEGORY_ID
GO

IF OBJECT_ID('FK_PROD_ID') IS NOT NULL
	ALTER TABLE dbo.SALES DROP CONSTRAINT FK_PROD_ID 
GO

IF OBJECT_ID('FK_CUST_ID') IS NOT NULL
	ALTER TABLE dbo.SALES DROP CONSTRAINT FK_CUST_ID
GO

IF OBJECT_ID('FK_CHANNEL_ID') IS NOT NULL
ALTER TABLE dbo.SALES DROP CONSTRAINT FK_CHANNEL_ID
GO

IF OBJECT_ID('FK_PROMO_ID') IS NOT NULL
	ALTER TABLE dbo.SALES DROP CONSTRAINT FK_PROMO_ID
GO

IF OBJECT_ID('PK_CHANNEL_ID') IS NOT NULL 
	ALTER TABLE dbo.CHANNELS DROP CONSTRAINT PK_CHANNEL_ID

IF OBJECT_ID('PK_CUST_INCOME_CATEGORY') IS NOT NULL
	ALTER TABLE dbo.CUSTOMERS_INCOME_LEVEL DROP CONSTRAINT PK_CUST_INCOME_CATEGORY
GO

IF OBJECT_ID('PK_COUNTRY_ID') IS NOT NULL 
	ALTER TABLE dbo.CUSTOMERS_COUNTRY DROP CONSTRAINT PK_COUNTRY_ID
GO

IF OBJECT_ID('PK_CUST_ID') IS NOT NULL
	ALTER TABLE dbo.CUSTOMERS DROP CONSTRAINT PK_CUST_ID
GO

IF OBJECT_ID('PK_PROD_SUBCATEGORY') IS NOT NULL
	ALTER TABLE dbo.PRODUCTS_CATEGORIES DROP CONSTRAINT PK_PROD_SUBCATEGORY
GO

IF OBJECT_ID('PK_PROD_ID') IS NOT NULL
	ALTER TABLE dbo.PRODUCTS DROP CONSTRAINT PK_PROD_ID
GO

IF OBJECT_ID('PK_PROMO_ID') IS NOT NULL
	ALTER TABLE dbo.PROMOTIONS DROP CONSTRAINT PK_PROMO_ID
GO

IF OBJECT_ID('PK_PROMO_SUBCATEGORY') IS NOT NULL
	ALTER TABLE dbo.PROMOTIONS_CATEGORIES DROP CONSTRAINT PK_PROMO_SUBCATEGORY
GO

IF OBJECT_ID('PK_SALESTRANS_ID') IS NOT NULL
	ALTER TABLE dbo.SALES DROP CONSTRAINT PK_SALESTRANS_ID
GO

/*
Drop all tables
*/
DROP TABLE IF EXISTS dbo.CHANNELS
GO

DROP TABLE IF EXISTS dbo.CUSTOMERS
GO

DROP TABLE IF EXISTS dbo.CUSTOMERS_COUNTRY
GO

DROP TABLE IF EXISTS dbo.CUSTOMERS_INCOME_LEVEL
GO

DROP TABLE IF EXISTS dbo.PRODUCTS_CATEGORIES
GO

DROP TABLE IF EXISTS dbo.PRODUCTS
GO

DROP TABLE IF EXISTS dbo.PROMOTIONS_CATEGORIES
GO

DROP TABLE IF EXISTS dbo.PROMOTIONS
GO

DROP TABLE IF EXISTS dbo.SALES
GO
