USE [2022DBFall_Group_1_DB]
GO

/*
Upload the data in CHANNELS table
*/
INSERT INTO dbo.CHANNELS SELECT CHANNEL_ID ,CHANNEL_DESC, CHANNEL_CLASS FROM LIY26.dbo.LI_CHANNELS
GO

/*
Upload the data in CUSTOMERS_COUNTRY table
*/
INSERT INTO dbo.CUSTOMERS_COUNTRY SELECT DISTINCT(COUNTRY_ID), COUNTRY_NAME, COUNTRY_REGION, COUNTRY_SUBREGION FROM LIY26.dbo.LI_CUSTOMERS_INTX
GO

/*
Upload the data in CUSTOMERS_INCOME_LEVEL table
*/
INSERT INTO dbo.CUSTOMERS_INCOME_LEVEL (CUST_INCOME_CATEGORY, CUST_INCOME_LOWER_LIMIT, CUST_INCOME_UPPER_LIMIT) VALUES ('G',130.000,149.999)
INSERT INTO dbo.CUSTOMERS_INCOME_LEVEL (CUST_INCOME_CATEGORY, CUST_INCOME_LOWER_LIMIT, CUST_INCOME_UPPER_LIMIT) VALUES ('A',0.000,30.000)
INSERT INTO dbo.CUSTOMERS_INCOME_LEVEL (CUST_INCOME_CATEGORY, CUST_INCOME_LOWER_LIMIT, CUST_INCOME_UPPER_LIMIT) VALUES ('J',190.000,249.999)
INSERT INTO dbo.CUSTOMERS_INCOME_LEVEL (CUST_INCOME_CATEGORY, CUST_INCOME_LOWER_LIMIT, CUST_INCOME_UPPER_LIMIT) VALUES ('K',250.000,299.999)
INSERT INTO dbo.CUSTOMERS_INCOME_LEVEL (CUST_INCOME_CATEGORY, CUST_INCOME_LOWER_LIMIT, CUST_INCOME_UPPER_LIMIT) VALUES ('L',300.000,NULL)
INSERT INTO dbo.CUSTOMERS_INCOME_LEVEL (CUST_INCOME_CATEGORY, CUST_INCOME_LOWER_LIMIT, CUST_INCOME_UPPER_LIMIT) VALUES ('F',110.000,129.999)
INSERT INTO dbo.CUSTOMERS_INCOME_LEVEL (CUST_INCOME_CATEGORY, CUST_INCOME_LOWER_LIMIT, CUST_INCOME_UPPER_LIMIT) VALUES ('D',70.000,89.999)
INSERT INTO dbo.CUSTOMERS_INCOME_LEVEL (CUST_INCOME_CATEGORY, CUST_INCOME_LOWER_LIMIT, CUST_INCOME_UPPER_LIMIT) VALUES ('E',90.000,109.999)
INSERT INTO dbo.CUSTOMERS_INCOME_LEVEL (CUST_INCOME_CATEGORY, CUST_INCOME_LOWER_LIMIT, CUST_INCOME_UPPER_LIMIT) VALUES ('C',50.000,69.999)
INSERT INTO dbo.CUSTOMERS_INCOME_LEVEL (CUST_INCOME_CATEGORY, CUST_INCOME_LOWER_LIMIT, CUST_INCOME_UPPER_LIMIT) VALUES ('I',170.000,189.999)
INSERT INTO dbo.CUSTOMERS_INCOME_LEVEL (CUST_INCOME_CATEGORY, CUST_INCOME_LOWER_LIMIT, CUST_INCOME_UPPER_LIMIT) VALUES ('B',30.000,49.999)
INSERT INTO dbo.CUSTOMERS_INCOME_LEVEL (CUST_INCOME_CATEGORY, CUST_INCOME_LOWER_LIMIT, CUST_INCOME_UPPER_LIMIT) VALUES ('H',150.000,169.999)
INSERT INTO dbo.CUSTOMERS_INCOME_LEVEL (CUST_INCOME_CATEGORY, CUST_INCOME_LOWER_LIMIT, CUST_INCOME_UPPER_LIMIT) VALUES ('M',0.000,NULL)
GO

/*
Upload the data in CUSTOMERS table
*/
INSERT INTO dbo.CUSTOMERS SELECT e.CUST_ID,i.CUST_FIRST_NAME ,i.CUST_LAST_NAME ,i.CUST_GENDER,e.CUST_YEAR_OF_BIRTH ,
CASE 
		WHEN e.CUST_MARITAL_STATUS IN ('married','Mar-AF')  THEN 'Married'
		WHEN e.CUST_MARITAL_STATUS IN ('single','Separ.') THEN 'Single'
		WHEN e.CUST_MARITAL_STATUS IN ('Widowed','widow') THEN 'Widowed'
		WHEN e.CUST_MARITAL_STATUS IN ('Divorc.','divorced') THEN 'Divorced'
		WHEN e.CUST_MARITAL_STATUS IN ('NeverM') THEN 'Never married'
		ELSE 'Prefer not to say'
END AS CUST_MARITAL_STATUS,
i.CUST_MAIN_PHONE_NUMBER,i.CUST_EMAIL,i.CUST_STREET_ADDRESS,
i.CUST_POSTAL_CODE,i.CUST_CITY,i.CUST_STATE_PROVINCE,
CASE
	WHEN e.CUST_INCOME_LEVEL = '' THEN 'M'
	ELSE SUBSTRING(e.CUST_INCOME_LEVEL, 2,1)
END AS CUST_INCOME_CATEGORY,
e.CUST_CREDIT_LIMIT ,i.COUNTRY_ID
FROM LIY26.dbo.LI_CUSTOMERS_INTX as i
	JOIN LIY26.dbo.LI_CUSTOMERS_EXT AS e
		ON i.CUST_ID = e.CUST_ID
GO

/*
Upload the data in PRODUCTS_CATEGORIES table
*/
INSERT INTO dbo.PRODUCTS_CATEGORIES 
SELECT 
DISTINCT(CASE 
	WHEN PROD_CATEGORY = 'Software/Other' AND PROD_SUBCATEGORY = 'Accessories' THEN 'Accessories-Software'
	ELSE PROD_SUBCATEGORY
END) as PROD_SUBCATEGORY, 
PROD_CATEGORY 
FROM LIY26.dbo.LI_PRODUCTS
GO

/*
Upload the data in PRODUCTS table
*/
INSERT INTO dbo.PRODUCTS
SELECT PROD_ID, 
(CASE
	WHEN PROD_ID = 123 THEN '"DVD-R Discs, 4.7GB, Pack of 5 - V2"'
	ELSE PROD_NAME
END) as PROD_NAME, 
PROD_DESC, PROD_LIST_PRICE, PROD_MIN_PRICE, PROD_SUBCATEGORY FROM LIY26.dbo.LI_PRODUCTS
GO

/*
Upload the data in PROMOTIONS_CATEGORIES table
*/
INSERT INTO dbo.PROMOTIONS_CATEGORIES SELECT DISTINCT(PROMO_SUBCATEGORY), PROMO_CATEGORY FROM LIY26.DBO.LI_PROMOTIONS
GO

/*
Upload the data in PROMOTIONS table
*/
INSERT INTO dbo.PROMOTIONS SELECT PROMO_ID, PROMO_NAME, PROMO_SUBCATEGORY, PROMO_COST, PROMO_BEGIN_DATE, PROMO_END_DATE FROM LIY26.DBO.LI_PROMOTIONS
GO

/*
Upload the data in SALES table
*/
INSERT INTO dbo.SALES
SELECT SALESTRANS_ID, PROD_ID, PROMO_ID, CUST_ID, CHANNEL_ID, SALE_DATE, SHIPPING_DATE, PAYMENT_DATE, QUANTITY_SOLD, AMOUNT_SOLD, UNIT_PRICE FROM LIY26.dbo.LI_SALES_12_13
UNION
SELECT SALESTRANS_ID, PROD_ID, PROMO_ID, CUST_ID, CHANNEL_ID, SALE_DATE, SHIPPING_DATE, PAYMENT_DATE, QUANTITY_SOLD, AMOUNT_SOLD, UNIT_PRICE FROM LIY26.dbo.LI_SALES_14
GO